In [54]:
import pandas as pd

#### THe Financial File

In [57]:
df = pd.read_csv('tech_financials_2021_2023.csv')

#### First 5 rows

In [60]:
df.head()

,Company,Fiscal Year,Total Revenue (B USD),Net Income (B USD),Total Assets (B USD),Total Liabilities (B USD),Cash Flow from Ops (B USD)
0,Microsoft,2023,211.915,72.361,411.550,198.250,87.635
1,Tesla,2023,96.773,14.997,140.473,48.390,14.923
2,Tesla,2022,81.462,12.556,82.338,48.450,13.256
3,Tesla,2021,53.823,5.519,62.131,48.450,5.644
4,Apple,2023,383.300,96.995,352.583,290.437,118.254

#### Last 5 rows

In [63]:
df.tail()

,Company,Fiscal Year,Total Revenue (B USD),Net Income (B USD),Total Assets (B USD),Total Liabilities (B USD),Cash Flow from Ops (B USD)
2,Tesla,2022,81.462,12.556,82.338,48.450,13.256
3,Tesla,2021,53.823,5.519,62.131,48.450,5.644
4,Apple,2023,383.300,96.995,352.583,290.437,118.254
5,Apple,2022,394.300,99.803,352.755,302.083,110.543
6,Apple,2021,365.000,94.680,NaN,NaN,NaN

In [65]:
df

,Company,Fiscal Year,Total Revenue (B USD),Net Income (B USD),Total Assets (B USD),Total Liabilities (B USD),Cash Flow from Ops (B USD)
0,Microsoft,2023,211.915,72.361,411.550,198.250,87.635
1,Tesla,2023,96.773,14.997,140.473,48.390,14.923
2,Tesla,2022,81.462,12.556,82.338,48.450,13.256
3,Tesla,2021,53.823,5.519,62.131,48.450,5.644
4,Apple,2023,383.300,96.995,352.583,290.437,118.254
5,Apple,2022,394.300,99.803,352.755,302.083,110.543
6,Apple,2021,365.000,94.680,NaN,NaN,NaN

In [67]:
df.columns

Index(['Company', 'Fiscal Year', 'Total Revenue (B USD)', 'Net Income (B USD)',
       'Total Assets (B USD)', 'Total Liabilities (B USD)',
       'Cash Flow from Ops (B USD)'],
      dtype='object')

#### finding missing values

In [70]:
df.isnull().sum()

Company                       0
Fiscal Year                   0
Total Revenue (B USD)         0
Net Income (B USD)            0
Total Assets (B USD)          1
Total Liabilities (B USD)     1
Cash Flow from Ops (B USD)    1
dtype: int64

In [73]:
df.rename(columns={
    "Total Revenue (B USD)": "Total_Revenue",
    "Net Income (B USD)": "Net_Income",
    "Total Assets (B USD)": "Total_Assets",
    "Total Liabilities (B USD)": "Total_Liabilities",
    "Cash Flow from Ops (B USD)": "Cash_Flow_Operations"
}, inplace=True)

In [96]:
df.fillna(0)

,Company,Fiscal Year,Total_Revenue,Net_Income,Total_Assets,Total_Liabilities,Cash_Flow_Operations,Revenue Growth(%),Net Income Growth(%)
0,Microsoft,2023,211.915,72.361,411.550,198.250,87.635,0.000000,0.000000
1,Tesla,2023,96.773,14.997,140.473,48.390,14.923,0.000000,0.000000
2,Tesla,2022,81.462,12.556,82.338,48.450,13.256,-15.821562,-16.276589
3,Tesla,2021,53.823,5.519,62.131,48.450,5.644,-33.928703,-56.044919
4,Apple,2023,383.300,96.995,352.583,290.437,118.254,0.000000,0.000000
5,Apple,2022,394.300,99.803,352.755,302.083,110.543,2.869815,2.894995
6,Apple,2021,365.000,94.680,352.755,302.083,110.543,-7.430890,-5.133112

#### Adding new columns

In [110]:
df['Revenue Growth(%)'] = df.groupby(['Fiscal Year'])['Total_Revenue'].pct_change()*100

In [112]:
df['Net Income Growth(%)'] = df.groupby(['Fiscal Year'])['Net_Income'].pct_change()*100

In [114]:
df['Revenue Growth(%)']

0           NaN
1    -54.334049
2           NaN
3           NaN
4    296.081552
5    384.029363
6    578.148747
Name: Revenue Growth(%), dtype: float64

In [116]:
df['Net Income Growth(%)']

0            NaN
1     -79.274747
2            NaN
3            NaN
4     546.762686
5     694.863014
6    1615.528175
Name: Net Income Growth(%), dtype: float64

In [108]:
df

,Company,Fiscal Year,Total_Revenue,Net_Income,Total_Assets,Total_Liabilities,Cash_Flow_Operations,Revenue Growth(%),Net Income Growth(%)
0,Microsoft,2023,211.915,72.361,411.550,198.250,87.635,NaN,NaN
1,Tesla,2023,96.773,14.997,140.473,48.390,14.923,NaN,NaN
2,Tesla,2022,81.462,12.556,82.338,48.450,13.256,-15.821562,-16.276589
3,Tesla,2021,53.823,5.519,62.131,48.450,5.644,-33.928703,-56.044919
4,Apple,2023,383.300,96.995,352.583,290.437,118.254,NaN,NaN
5,Apple,2022,394.300,99.803,352.755,302.083,110.543,2.869815,2.894995
6,Apple,2021,365.000,94.680,352.755,302.083,110.543,-7.430890,-5.133112